export * from "./Head";
export * from "./SectionTitle";
export * from "./Sections/About";
export * from "./Sections/HomePortfolio";
export * from "./Sections/Projects";
export * from "./Sections/Skills";
export * from "./UI/ButtonTop";
export * from "./UI/Footer";
export * from "./UI/Navbar";
